services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline
    networks:
      - net1
  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      - xpack.monitoring.enabled=false
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - net1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - net1

  restserver:
    build:
      context: ./restServer
      dockerfile: Dockerfile
    

    container_name: restserver
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - net1
    

volumes:
  es_data:
    driver: local

networks:
  net1:
    external: true
